### ISSUE TITLE
Error: Cannot find module 'mysql'

### ISSUE THREAD

**Issue by iqtak** [MrPancakers/ragemp-mysql#3]
Hej , i try on linux start but have this issues !!
What to do 4 fix ? 
------------------------------------ srv log ------------------------------------

[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:22005
Loading packages
	"mysql" loaded
Error: Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ragemp-srv/packages/mysql/mysql.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
[P] Plugin bridge.so loaded!
Started HTTP server at 22006 port.

**Comment by iqtak** [comment]
+ i dont add any code to this sql master

**Comment by MrPancakers** [comment]
You haven't installed the npm modules as outlined in the instructions. If you need further help contact through the forums.
